apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-jobs
  namespace: gen
rules:
- apiGroups:
    - batch
  resources: 
    - jobs
  verbs:
    - create
    - get
    - list
    - patch