apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: get-services
  namespace: gen
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: get-services
subjects:
- kind: ServiceAccount
  name: default
  namespace: gen