apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-database
  namespace: gen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-database
  template:
    metadata:
      labels:
        app: image-database
    spec:
      containers:
        - name: image-database
          image: $IMAGE_DATABASE_IMAGE
          ports:
            - containerPort: 8080
          env:
            - name: CLICKHOUSE_HOST
              value: $CLICKHOUSE_HOST
            - name: CLICKHOUSE_PORT
              value: "$CLICKHOUSE_PORT"
            - name: CLICKHOUSE_DATABASE
              value: $CLICKHOUSE_DATABASE
            - name: CLICKHOUSE_USERNAME
              value: $CLICKHOUSE_USERNAME
            - name: CLICKHOUSE_PASSWORD
              value: $CLICKHOUSE_PASSWORD
# TODO: switch password etc to secrets