services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'CLICKHOUSE_DB=mydb'
      - 'CLICKHOUSE_PASSWORD=password'
      - 'CLICKHOUSE_USER=postgres'
    ports:
      - '5432:5432'
